name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      working-directory: ${{runner.workspace}}
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      working-directory: ${{runner.workspace}}
      run: cmake --build build --config ${{env.BUILD_TYPE}}
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:    
    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      run: ctest -C ${{env.BUILD_TYPE}}
